project:
  type: book

book:
  title: "book"
  author: "Jane Doe"
  date: "2023-01-21"
  chapters:
    - index.qmd
    - intro.qmd
    - usingrich.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



